CRUD
galy4/learnSpringRepo pull request #2
Opened 2021-09-09 09:53 UTC by galy4

готово. Вопросы есть, но немного.

2021-09-16 05:17 UTC, galy4 commented on src/main/java/com/example/demo/rest/PersonController.java
> +
коммент

2021-10-06 03:10 UTC, ydvorzhetskiy requested changes

2021-10-13 06:09 UTC, galy4 commented on src/main/java/com/example/demo/rest/dto/PersonRepository.java
> +    public int insertBook(BookDto book, PersonDto personDto) {
преобразования добавил, выглядит странно. Наверняка можно красивее

2021-10-13 08:48 UTC, galy4 commented on src/main/java/com/example/demo/rest/dto/PersonRepository.java
> +                book.getAuthor(), book.getTitle(), personDto.getId());
done

2021-11-03 06:09 UTC, ydvorzhetskiy approved these changes

2021-11-03 11:33 UTC, merged